// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(BackendDbContext))]
    [Migration("20250826142628_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Alocacao", b =>
                {
                    b.Property<long>("IdAlocacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdAlocacao"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRecurso")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoRecurso")
                        .HasColumnType("integer");

                    b.HasKey("IdAlocacao");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Alocacoes");

                    b.HasData(
                        new
                        {
                            IdAlocacao = 1L,
                            DataCriacao = new DateTime(2025, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataReserva = new DateTime(2025, 8, 27, 3, 0, 0, 0, DateTimeKind.Utc),
                            FuncionarioId = 1L,
                            IdRecurso = 1L,
                            TipoRecurso = 0
                        },
                        new
                        {
                            IdAlocacao = 2L,
                            DataCriacao = new DateTime(2025, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataReserva = new DateTime(2025, 8, 28, 3, 0, 0, 0, DateTimeKind.Utc),
                            FuncionarioId = 2L,
                            IdRecurso = 2L,
                            TipoRecurso = 2
                        },
                        new
                        {
                            IdAlocacao = 3L,
                            DataCriacao = new DateTime(2025, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataReserva = new DateTime(2025, 8, 29, 3, 0, 0, 0, DateTimeKind.Utc),
                            FuncionarioId = 3L,
                            IdRecurso = 4L,
                            TipoRecurso = 1
                        },
                        new
                        {
                            IdAlocacao = 4L,
                            DataCriacao = new DateTime(2025, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataReserva = new DateTime(2025, 8, 30, 3, 0, 0, 0, DateTimeKind.Utc),
                            FuncionarioId = 4L,
                            IdRecurso = 4L,
                            TipoRecurso = 0
                        },
                        new
                        {
                            IdAlocacao = 5L,
                            DataCriacao = new DateTime(2025, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            DataReserva = new DateTime(2025, 8, 31, 3, 0, 0, 0, DateTimeKind.Utc),
                            FuncionarioId = 5L,
                            IdRecurso = 1L,
                            TipoRecurso = 2
                        });
                });

            modelBuilder.Entity("backend.Models.Funcionario", b =>
                {
                    b.Property<long>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdFuncionario"));

                    b.Property<int>("Cargo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Matricula")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdFuncionario");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            IdFuncionario = 1L,
                            Cargo = 2,
                            DataAdmissao = new DateTime(2025, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Matricula = 100167,
                            Nome = "Nicholas Navarro"
                        },
                        new
                        {
                            IdFuncionario = 2L,
                            Cargo = 2,
                            DataAdmissao = new DateTime(2025, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Matricula = 100168,
                            Nome = "Júlia Schivisnky"
                        },
                        new
                        {
                            IdFuncionario = 3L,
                            Cargo = 2,
                            DataAdmissao = new DateTime(2025, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Matricula = 100169,
                            Nome = "Ellen"
                        },
                        new
                        {
                            IdFuncionario = 4L,
                            Cargo = 2,
                            DataAdmissao = new DateTime(2025, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Matricula = 100170,
                            Nome = "Henrique Coralles"
                        },
                        new
                        {
                            IdFuncionario = 5L,
                            Cargo = 1,
                            DataAdmissao = new DateTime(2025, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Matricula = 101010,
                            Nome = "MR Gabriel Velloso"
                        });
                });

            modelBuilder.Entity("backend.Models.Laboratorio", b =>
                {
                    b.Property<long>("IdLaboratorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdLaboratorio"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QtdComputadores")
                        .HasColumnType("integer");

                    b.HasKey("IdLaboratorio");

                    b.ToTable("Laboratorios");

                    b.HasData(
                        new
                        {
                            IdLaboratorio = 1L,
                            Descricao = "Computadores Core i5, 8GB RAM",
                            Nome = "Lab Redes",
                            QtdComputadores = 20
                        },
                        new
                        {
                            IdLaboratorio = 2L,
                            Descricao = "Core i7, 16GB RAM, SSD",
                            Nome = "Lab Desenvolvimento",
                            QtdComputadores = 25
                        },
                        new
                        {
                            IdLaboratorio = 3L,
                            Descricao = "Core i5, 8GB RAM, kits de hardware",
                            Nome = "Lab Hardware",
                            QtdComputadores = 15
                        },
                        new
                        {
                            IdLaboratorio = 4L,
                            Descricao = "Core i9, 32GB RAM, GPU dedicada",
                            Nome = "Lab Inteligência Artificial",
                            QtdComputadores = 10
                        },
                        new
                        {
                            IdLaboratorio = 5L,
                            Descricao = "Core i5, 16GB RAM",
                            Nome = "Lab Banco de Dados",
                            QtdComputadores = 18
                        });
                });

            modelBuilder.Entity("backend.Models.Notebook", b =>
                {
                    b.Property<long>("IdNotebook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdNotebook"));

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroPatrimonio")
                        .HasColumnType("integer");

                    b.HasKey("IdNotebook");

                    b.ToTable("Notebooks");

                    b.HasData(
                        new
                        {
                            IdNotebook = 1L,
                            DataAquisicao = new DateTime(2023, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Dell Inspiron i5",
                            NumeroPatrimonio = 1001
                        },
                        new
                        {
                            IdNotebook = 2L,
                            DataAquisicao = new DateTime(2022, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "HP Elitebook i7",
                            NumeroPatrimonio = 1002
                        },
                        new
                        {
                            IdNotebook = 3L,
                            DataAquisicao = new DateTime(2024, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Lenovo Thinkpad i5",
                            NumeroPatrimonio = 1003
                        },
                        new
                        {
                            IdNotebook = 4L,
                            DataAquisicao = new DateTime(2021, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Acer Aspire i3",
                            NumeroPatrimonio = 1004
                        },
                        new
                        {
                            IdNotebook = 5L,
                            DataAquisicao = new DateTime(2019, 8, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Macbook Air M1",
                            NumeroPatrimonio = 1005
                        });
                });

            modelBuilder.Entity("backend.Models.Sala", b =>
                {
                    b.Property<long>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdSala"));

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("QtdLugares")
                        .HasColumnType("integer");

                    b.Property<bool>("TemProjetor")
                        .HasColumnType("boolean");

                    b.HasKey("IdSala");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            IdSala = 1L,
                            Numero = 101,
                            QtdLugares = 30,
                            TemProjetor = true
                        },
                        new
                        {
                            IdSala = 2L,
                            Numero = 102,
                            QtdLugares = 20,
                            TemProjetor = false
                        },
                        new
                        {
                            IdSala = 3L,
                            Numero = 103,
                            QtdLugares = 25,
                            TemProjetor = true
                        },
                        new
                        {
                            IdSala = 4L,
                            Numero = 104,
                            QtdLugares = 15,
                            TemProjetor = false
                        },
                        new
                        {
                            IdSala = 5L,
                            Numero = 105,
                            QtdLugares = 40,
                            TemProjetor = true
                        });
                });

            modelBuilder.Entity("backend.Models.Alocacao", b =>
                {
                    b.HasOne("backend.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
