// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(BackendDbContext))]
    partial class BackendDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Alocacao", b =>
                {
                    b.Property<long>("IdAlocacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdAlocacao"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdFuncionario")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRecurso")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoRecurso")
                        .HasColumnType("integer");

                    b.HasKey("IdAlocacao");

                    b.ToTable("Alocacoes");
                });

            modelBuilder.Entity("backend.Models.Funcionario", b =>
                {
                    b.Property<long>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdFuncionario"));

                    b.Property<int>("Cargo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Matricula")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdFuncionario");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("backend.Models.Laboratorio", b =>
                {
                    b.Property<long>("IdLaboratorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdLaboratorio"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QtdComputadores")
                        .HasColumnType("integer");

                    b.HasKey("IdLaboratorio");

                    b.ToTable("Laboratorios");
                });

            modelBuilder.Entity("backend.Models.Notebook", b =>
                {
                    b.Property<long>("IdNotebook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdNotebook"));

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroPatrimonio")
                        .HasColumnType("integer");

                    b.HasKey("IdNotebook");

                    b.ToTable("Notebooks");
                });

            modelBuilder.Entity("backend.Models.Sala", b =>
                {
                    b.Property<long>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdSala"));

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<bool>("TemProjetor")
                        .HasColumnType("boolean");

                    b.HasKey("IdSala");

                    b.ToTable("Salas");
                });
#pragma warning restore 612, 618
        }
    }
}
